### ISSUE TITLE
Light mode still doesn't work, kinda

### ISSUE THREAD

**Issue by ClammyMantis488** [JoshuaDoes/zPlayer#1]
The icons do not invert. You probably already knew this though. Also when flipping between modes and playing music it stops for half a second.

**Comment by JoshuaDoes** [comment]
The icons don't yet invert as I currently do not have the icons for the light theme, as seen in ``.\assets\icons\icons8\`` (there are no ``White-*.ico`` files), but these will be available soon. As for the music stopping, that's simply because of the UI change happening all in one set of instructions, which may interrupt any other instructions currently being ran until they have finished.

**Comment by JoshuaDoes** [comment]
I'm happy to announce that zPlayer Preview Build 23 will feature three stock themes (and custom theme support!): Dark, Light, and Nolan. All three themes utilize icons from [Icons8](https://icons8.com/), and soon there will be an entire theme store to upload/download user-created themes c:
